# Generated by Django 3.0.3 on 2020-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', help_text='Unique number of order e.g. COV27622', max_length=50, verbose_name='Order Number')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Number of commissions', verbose_name='Quantity (Pcs)')),
                ('size', models.FloatField(default=0.0, help_text='Total size of lot in square feet.', verbose_name='Quantity (Sq.Ft.)')),
                ('color', models.CharField(choices=[('black', 'Black'), ('biege', 'Biege'), ('white', 'White')], default='black', help_text='Color of the lot.', max_length=50, verbose_name='Color')),
            ],
        ),
    ]
