# Generated by Django 3.0.3 on 2020-02-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Unique number of kit e.g. 27', unique=True, verbose_name='Kit Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('completed', 'Completed'), ('dispatched', 'Dispatched')], default='pending', help_text='Status of the Kit', max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='', help_text='Unique number of order e.g. COV27622', max_length=50, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Reference order number (if available)', max_length=50, verbose_name='Ref. Order No'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipby',
            field=models.DateField(blank=True, help_text='Expected shipping date for the order.', null=True, verbose_name='Ship By (optional)'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', help_text='Identifier for Product e.g. PatioFirepitCover0037.', max_length=100, verbose_name='Product Number')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Number of commissions', verbose_name='Quantity (Pcs)')),
                ('size', models.FloatField(default=0.0, help_text='Total size of product in square feet.', verbose_name='Quantity (Sq.Ft.)')),
                ('fabric', models.CharField(choices=[('max', 'Cover MAX'), ('tuff', 'Cover TUFF')], help_text='Fabric to be used to complete order.', max_length=10)),
                ('color', models.CharField(choices=[('black', 'Black'), ('biege', 'Biege'), ('white', 'White')], default='black', help_text='Color of the lot.', max_length=50, verbose_name='Color')),
                ('kit', models.ForeignKey(help_text='Kit number that this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='expert.Kit')),
                ('order', models.ForeignKey(help_text='Order that this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='expert.Order')),
            ],
        ),
    ]
