# Generated by Django 3.0.3 on 2020-02-05 12:43

from django.db import migrations, models
import expert.models
import kit.models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='original_kit_summary',
            field=models.FileField(help_text='Upload the jpg of the original/unmodified image of kit summary', null=True, upload_to=kit.models.kit_image_path, verbose_name='Original KIT Image'),
        ),
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Full Address of the worker.'),
        ),
        migrations.AddField(
            model_name='worker',
            name='joined',
            field=models.DateField(help_text='Date of joining.', null=True, verbose_name='Joined since'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('biege', 'Biege'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray')], default='black', help_text='Color of the lot.', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
