# Generated by Django 3.0.3 on 2020-02-05 13:12

from django.db import migrations, models
import django.db.models.deletion
import expert.models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20200205_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='completedby',
            field=models.ForeignKey(blank=True, help_text='worker that completed this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_completed', to='expert.Worker'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='original_kit_summary',
            field=models.FileField(blank=True, help_text='Upload the jpg of the original/unmodified image of kit summary', null=True, upload_to=expert.models.kit_image_path, verbose_name='Original KIT Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.ForeignKey(help_text='Kit that this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='expert.Kit'),
        ),
    ]
