# Generated by Django 3.0.3 on 2020-02-06 12:25

from django.db import migrations, models
import expert.models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_product_completeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='original_kit_summary',
            field=models.ImageField(blank=True, help_text='Upload the jpg of the original/unmodified image of kit summary', null=True, upload_to=expert.models.kit_image_path, verbose_name='Original KIT Image'),
        ),
    ]
