# Generated by Django 3.0.3 on 2020-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_auto_20200208_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.CharField(default='', help_text='Unique number of order e.g. COV27622', max_length=50, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.FloatField(default=0.0, help_text='Total size of product in square feet.', verbose_name='Size (Sq.Ft.)'),
        ),
    ]
