# Generated by Django 3.0.3 on 2020-02-10 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_auto_20200210_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='date_received',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date at which KIT is received.', verbose_name='Date Received'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='date_sent',
            field=models.DateField(blank=True, help_text='Date at which KIT is completed and dispatched', null=True, verbose_name='Date dispatched'),
        ),
    ]
