# Generated by Django 3.0.5 on 2020-04-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0014_auto_20200211_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='completeddate',
            new_name='date_completed',
        ),
    ]
