# Generated by Django 3.0.5 on 2020-04-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_auto_20200402_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='joined',
            new_name='date_joined',
        ),
    ]
