# Generated by Django 3.0.5 on 2020-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_auto_20200402_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='data',
            field=models.TextField(blank=True, default='', help_text='Copy paste the excel rows containing the product data', verbose_name='Excel Data'),
        ),
    ]
