# Generated by Django 3.0.5 on 2020-04-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0017_kit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('beige', 'Beige'), ('blue', 'Blue'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray')], default='black', help_text='Color of the lot.', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_number',
            field=models.CharField(default='', help_text='Number of order e.g. COV27622', max_length=50, verbose_name='Order Number'),
        ),
    ]
