# Generated by Django 3.0.5 on 2020-04-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0018_auto_20200403_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', help_text='Status of the Product', max_length=50, verbose_name='Status'),
        ),
    ]
