# Generated by Django 3.0.5 on 2020-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0020_auto_20200404_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('beige', 'Beige'), ('blue', 'Blue'), ('white', 'White'), ('brown', 'Brown'), ('green', 'Green'), ('sand', 'Sand'), ('burgundy', 'Burgundy'), ('gray', 'Gray'), ('clear', 'Clear'), ('olive_green', 'Olive Green'), ('light_sand', 'Light Sand'), ('light_gray', 'Light Gray'), ('coffee_brown', 'Coffee Brown')], default='black', help_text='Color of the lot.', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('max', 'Cover MAX'), ('tuff', 'Cover TUFF'), ('fab', 'Cover Fab'), ('clear', 'Cover Clear')], help_text='Fabric to be used to complete order.', max_length=10),
        ),
    ]
