# Generated by Django 3.0.5 on 2020-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0021_auto_20200404_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the Worker Active?', verbose_name='Is Active?'),
        ),
    ]
