# Generated by Django 3.0.5 on 2020-04-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0022_worker_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Unique number of each delivery challan', unique=True, verbose_name='Challan Number')),
                ('date_sent', models.DateField(help_text='Date at which this challan is dispatched', null=True, verbose_name='Date of Dispatch')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='challan',
            field=models.ForeignKey(default=None, help_text='Challan that this product is dispatched through', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='expert.Challan'),
        ),
    ]
