# Generated by Django 3.0.5 on 2020-04-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0024_auto_20200404_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='date_sent',
        ),
    ]
