# Generated by Django 3.0.5 on 2020-04-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0025_remove_kit_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_remark',
            field=models.CharField(choices=[('', ''), ('unprocessed', 'UnProcessed'), ('semiprocessed', 'Semi-Processed'), ('mistake', 'Cutting Mistake')], default='', help_text='Select the appropriate remark for returned products', max_length=200, verbose_name='Return Remarks'),
        ),
    ]
