# Generated by Django 3.0.5 on 2020-04-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0028_auto_20200406_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='challan',
            field=models.ForeignKey(blank=True, default=None, help_text='Challan that this product is dispatched through', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='expert.Challan'),
        ),
    ]
