# Generated by Django 3.0.5 on 2020-04-07 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0029_auto_20200406_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
