# Generated by Django 3.0.5 on 2020-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0030_product_creation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='date_product_completion',
            field=models.DateField(blank=True, help_text='Manual Date which can be set so that all the products             in this kit will be completed on this date', null=True, verbose_name='Product Completion Date'),
        ),
    ]
