# Generated by Django 3.0.5 on 2020-04-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0031_kit_date_product_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Unique number of each delivery invoice', unique=True, verbose_name='Invoice Number')),
                ('date_sent', models.DateField(help_text='Date at which this invoice was created and dispatched', null=True, verbose_name='Date of Dispatch')),
            ],
        ),
        migrations.AddField(
            model_name='challan',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, help_text='The Invoice to which this challan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='expert.Invoice'),
        ),
    ]
