# Generated by Django 3.0.5 on 2020-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0034_kit_jobwork_gatepass_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', help_text='Aadhar number of the worker registered. (Enter without any space or delimiter)', max_length=12, verbose_name='Aadhar #'),
        ),
        migrations.AddField(
            model_name='worker',
            name='mobile_number',
            field=models.CharField(blank=True, default='', help_text='10-digit mobile number of the worker without leading zero(s)', max_length=20, verbose_name='Mobile #'),
        ),
    ]
