# Generated by Django 3.0.5 on 2020-04-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0036_auto_20200425_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('assign_product', 'Can Assign a worker to product'), ('complete_product', 'Can Complete a product')]},
        ),
    ]
