# Generated by Django 3.0.5 on 2020-04-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0039_product_dispatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='username',
            new_name='_username',
        ),
    ]
