# Generated by Django 3.0.5 on 2020-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0041_auto_20200429_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_remark',
            field=models.CharField(blank=True, choices=[('', ''), ('unprocessed', 'UnProcessed'), ('semiprocessed', 'Semi-Processed'), ('mistake', 'Cutting Mistake'), ('fault', 'Fault')], default='', help_text='Select the appropriate remark for returned products', max_length=200, verbose_name='Return Remarks'),
        ),
    ]
