# Generated by Django 3.0.5 on 2020-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0042_auto_20200430_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('max', 'Cover MAX'), ('tuff', 'Cover TUFF'), ('fab', 'Cover Fab'), ('clear', 'Cover Clear')], help_text='Fabric to be used to complete order.', max_length=10, verbose_name='Fabric'),
        ),
    ]
