# Generated by Django 3.0.5 on 2020-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0044_auto_20200505_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of the company or Individual', max_length=100, verbose_name='Name')),
            ],
        ),
    ]
