# Generated by Django 3.0.5 on 2020-05-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0045_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='customer',
            field=models.OneToOneField(default=None, help_text='The customer for against whom challan is drawn', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='expert.Customer'),
        ),
    ]
