# Generated by Django 3.0.5 on 2020-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0048_auto_20200506_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
