# Generated by Django 3.0.5 on 2020-05-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('expert', '0052_auto_20200507_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, help_text='The Invoice to which this challan belongs to', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='challans', to='invoice.Invoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
