# Generated by Django 3.0.5 on 2020-05-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0053_auto_20200507_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assignedto',
            field=models.ForeignKey(blank=True, default=None, help_text='Worker that is assigned to this product', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products_assigned', to='expert.Worker', verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='product',
            name='completedby',
            field=models.ForeignKey(blank=True, default=None, help_text='worker that completed this product', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products_completed', to='expert.Worker', verbose_name='Completed By'),
        ),
    ]
