# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0054_auto_20200509_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assignedto',
            field=models.IntegerField(blank=True, default=None, help_text='Worker that is assigned to this product', null=True, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='product',
            name='completedby',
            field=models.IntegerField(blank=True, default=None, help_text='worker that completed this product', null=True, verbose_name='Completed By'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
