# Generated by Django 3.0.5 on 2020-05-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0056_auto_20200509_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='challan',
            field=models.ForeignKey(blank=True, default=None, help_text='Challan that this product is dispatched through', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='expert.Challan'),
        ),
    ]
