# Generated by Django 3.0.5 on 2020-05-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0059_auto_20200509_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='date_return',
            field=models.DateField(blank=True, help_text='Date at which KIT is expected to be returned in format (YYYY-MM-DD).', null=True, verbose_name='Expected Return Date'),
        ),
        migrations.AddField(
            model_name='kit',
            name='date_shipped',
            field=models.DateField(blank=True, help_text='Date at which KIT is shipped from customer in format (YYYY-MM-DD).', null=True, verbose_name='Shipping Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Verbose product name as received from supervisor', max_length=200, verbose_name='Product Name'),
        ),
    ]
