# Generated by Django 3.0.5 on 2020-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0060_auto_20200521_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='date_shipped',
            field=models.DateField(blank=True, help_text='Date at which KIT is to be shipped to customer in format (YYYY-MM-DD).', null=True, verbose_name='Shipping Date'),
        ),
    ]
