# Generated by Django 3.0.5 on 2020-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0062_auto_20200521_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_remark',
            field=models.CharField(blank=True, choices=[('', ''), ('unprocessed', 'UnProcessed'), ('semiprocessed', 'Semi-Processed'), ('mistake', 'Cutting Mistake'), ('damaged', 'Damaged Goods'), ('fault', 'Fault')], default='', help_text='Select the appropriate remark for returned products', max_length=200, verbose_name='Return Remarks'),
        ),
    ]
