# Generated by Django 3.0.5 on 2020-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0064_auto_20200521_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.IntegerField(help_text='Kit that this product belongs to.'),
        ),
    ]
