# Generated by Django 3.0.5 on 2020-05-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0065_auto_20200523_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
