# Generated by Django 3.0.5 on 2020-05-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
        ('expert', '0066_delete_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.ForeignKey(help_text='Kit that this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kit.Kit'),
        ),
    ]
