# Generated by Django 3.0.5 on 2020-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0067_auto_20200523_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.CharField(blank=True, default='', help_text='Additional remark for the Product', max_length=300, verbose_name='Remark'),
        ),
    ]
