# Generated by Django 3.0.5 on 2020-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0068_product_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_remark',
            field=models.CharField(blank=True, choices=[('', ''), ('unprocessed', 'UnProcessed'), ('semiprocessed', 'Semi-Processed'), ('mistake', 'Cutting Mistake'), ('damaged', 'Damaged Goods'), ('reject', 'Rejected'), ('rework', 'Re-Worked'), ('fault', 'Fault')], default='', help_text='Select the appropriate remark for returned products', max_length=200, verbose_name='Return Remarks'),
        ),
    ]
