# Generated by Django 3.0.5 on 2020-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0069_auto_20200602_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assignedto',
            field=models.IntegerField(blank=True, default=None, help_text='Worker that is assigned to this product', null=True, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='product',
            name='challan',
            field=models.IntegerField(blank=True, default=None, help_text='Challan that this product is dispatched through', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='completedby',
            field=models.IntegerField(blank=True, default=None, help_text='worker that completed this product', null=True, verbose_name='Completed By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.IntegerField(help_text='Kit that this product belongs to.'),
        ),
    ]
