# Generated by Django 3.0.5 on 2020-06-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0070_auto_20200603_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
