# Generated by Django 3.0.5 on 2020-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Name of the company or Individual', max_length=100, verbose_name='Name')),
                ('address1', models.CharField(blank=True, default='', max_length=200, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, default='', max_length=200, verbose_name='Address Line 2')),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('gstn', models.CharField(blank=True, default='N/A', help_text='GST Number of the customer', max_length=18, verbose_name='GSTN')),
                ('iec', models.CharField(blank=True, default='N/A', help_text='IEC Number of the customer as included in Challan', max_length=20, verbose_name='IEC')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
