# Generated by Django 3.0.5 on 2020-05-25 16:36

import challan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='jobwork_gatepass_processed',
            field=models.ImageField(blank=True, help_text='The field for storing the gate pass after it is processed', null=True, upload_to=challan.models.challan_image_path, verbose_name='Jobwork GatePass (Processed)'),
        ),
    ]
