# Generated by Django 3.0.5 on 2020-05-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0003_auto_20200526_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challan',
            options={'ordering': ('-number',)},
        ),
    ]
