# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import worker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('_username', models.CharField(default='', help_text='Username for worker login (unique for each worker)', max_length=100, verbose_name='Username')),
                ('address', models.TextField(blank=True, default='', help_text='Full Address of the worker.')),
                ('date_joined', models.DateField(help_text='Date of joining.', null=True, verbose_name='Joined since')),
                ('aadhar_number', models.CharField(blank=True, default='', help_text='Aadhar number of the worker registered. (Enter without any space or delimiter)', max_length=12, verbose_name='Aadhar #')),
                ('mobile_number', models.CharField(blank=True, default='', help_text='10-digit mobile number of the worker without leading zero(s)', max_length=20, verbose_name='Mobile #')),
                ('photo', models.ImageField(blank=True, help_text='Passport size profile picture for worker.', null=True, upload_to=worker.models.worker_image_path)),
                ('active', models.BooleanField(default=True, help_text='Is the Worker Active?', verbose_name='Is Active?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_profile', 'Worker can view thier own profile')],
            },
        ),
    ]
