# Generated by Django 3.0.5 on 2020-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fixed_rate',
            field=models.IntegerField(default=0, help_text='Total Monthly salary (without decimal places)', verbose_name='Monthly Salary'),
        ),
        migrations.AddField(
            model_name='worker',
            name='variable_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Rate of the worker per Sq.Ft.', max_digits=4, verbose_name='SqFt Rate'),
        ),
    ]
