# Generated by Django 3.0.5 on 2020-05-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20200512_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Select any date of the month for given month', verbose_name='For Month')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='worker.Worker')),
            ],
        ),
    ]
