# Generated by Django 3.0.5 on 2020-05-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
