# Generated by Django 3.0.5 on 2020-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fixed_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Daily salary (without decimal places)', max_digits=6, verbose_name='Daily Salary'),
        ),
    ]
