# Generated by Django 3.0.5 on 2020-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20200512_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_left',
            field=models.DateField(blank=True, help_text='Date at which this worker was fired', null=True, verbose_name='Date Left'),
        ),
    ]
