# Generated by Django 3.0.5 on 2020-05-23 09:04

from django.db import migrations, models
import kit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Unique number of kit from delivery challan.', unique=True, verbose_name='Kit Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('completed', 'Completed'), ('dispatched', 'Dispatched')], default='pending', help_text='Status of the Kit', max_length=50, verbose_name='Status')),
                ('date_received', models.DateField(blank=True, help_text='Date at which KIT is received in format (YYYY-MM-DD).', null=True, verbose_name='Date Received')),
                ('date_return', models.DateField(blank=True, help_text='Date at which KIT is expected to be returned in format (YYYY-MM-DD).', null=True, verbose_name='Expected Return Date')),
                ('date_product_completion', models.DateField(blank=True, help_text='Manual Date which can be set so that all the products             in this kit will be completed on this date', null=True, verbose_name='Product Completion Date')),
                ('data', models.TextField(blank=True, default='', help_text='Copy paste the excel rows containing the product data', verbose_name='Excel Data')),
                ('original_kit_summary', models.ImageField(blank=True, help_text='Upload the jpg of the original/unmodified image of kit summary', null=True, upload_to=kit.models.kit_image_path, verbose_name='Original KIT Image')),
                ('jobwork_challan', models.ImageField(blank=True, help_text='Upload the jpg/png image of the jobwork challan that came with kit.', null=True, upload_to=kit.models.kit_image_path, verbose_name='Jobwork Challan Image')),
                ('ewaybill', models.ImageField(blank=True, help_text='GSTN E-Way Bill that came with the kit', null=True, upload_to=kit.models.kit_image_path, verbose_name='E-Way Bill')),
                ('jobwork_gatepass', models.ImageField(blank=True, help_text='Upload the original jpg/png of the jobwork gatepass that came with kit', null=True, upload_to=kit.models.kit_image_path, verbose_name='Jobwork Gate Pass')),
                ('jobwork_gatepass_processed', models.ImageField(blank=True, help_text='The field for storing the gate pass after it is processed', null=True, upload_to=kit.models.kit_image_path, verbose_name='Jobwork GatePass (Processed)')),
            ],
        ),
    ]
