# Generated by Django 3.0.5 on 2020-05-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='jobwork_gatepass_processed',
        ),
    ]
