# Generated by Django 3.0.5 on 2020-05-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0005_auto_20200512_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('date_from', models.DateField(verbose_name='From Date')),
                ('date_to', models.DateField(verbose_name='To Date')),
                ('_fixed_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Daily salary (without decimal places)', max_digits=6, verbose_name='Daily Salary')),
                ('_variable_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Rate of the worker per Sq.Ft.', max_digits=4, verbose_name='SqFt Rate')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='worker.Worker')),
            ],
        ),
    ]
