# Generated by Django 3.0.5 on 2020-05-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='amount',
            new_name='_amount',
        ),
    ]
