# Generated by Django 3.0.5 on 2020-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Unique number of each delivery invoice', unique=True, verbose_name='Invoice Number')),
                ('date_sent', models.DateField(help_text='Date at which this invoice was created and dispatched', null=True, verbose_name='Date of Dispatch')),
                ('motor_vehicle_number', models.CharField(default='', help_text='Vehicle number from which the invoice is dispatched', max_length=100, verbose_name='Motor Vehicle No.')),
                ('destination', models.CharField(default='', help_text='Detination to which this invoice is dispatched', max_length=100)),
            ],
        ),
    ]
